"""Add an evidence-bounded brief to the boutique hotel furniture case."""
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

BRIEFS = {
    "tw": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">旅宿家具整合需求、可追溯範圍與交付邊界</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>客戶問題／來源狀態</h3><p>來源記錄台北市中心 28 間客房的精品旅宿，六個樓層以 Idea、Notation、Reason、Type 等概念區分；原始資料沒有足夠細節核對客戶問題，因此不從照片推定。</p></article><article class=\"location-card reveal\"><h3>空間與家具範圍</h3><p>可核對的客房家具包含衣櫃、飲料迷你吧、書桌、邊桌、床頭板與床架，設計方向是在經典與現代之間建立一致的旅宿家具語彙。</p></article><article class=\"location-card reveal\"><h3>材質與設計語彙</h3><p>expanded mesh 是主要設計元素，來源列出 mesh + wood、mesh + pipe、mesh + lighting、mesh + pattern 等異材質組合方向；正式材料牌號與表面處理仍需依圖面確認。</p></article><article class=\"location-card reveal\"><h3>Big Fame 可核對範圍</h3><p>文件描述 Big Fame 參與家具系列發展，以及材質與造型語彙整合；來源未核准完整合約分工、製造責任、現場安裝或最終交付責任。</p></article><article class=\"location-card reveal\"><h3>數量、交期與交付地</h3><p>28 間客房是來源中的空間背景，不等同已確認的家具採購數量。圖面版本、材料規格、樣品、交期、交付地與最終交付範圍，均需依新專案重新確認。</p></article><article class=\"location-card reveal\"><h3>成果與公開邊界</h3><p>這是可追溯的旅宿家具設計與系列開發紀錄，不等同已核准的客戶安裝或完整交付成果；客戶授權、價格、數量與實際成效未由來源確認。</p></article></div><p class=\"section-note reveal\">若要規劃旅宿客房家具，請先提供房型與數量、家具清單、空間概念、尺寸、材質方向、目標時程與交付地，Big Fame 再確認整合與製作條件。</p></div></section>""",
    "en": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">Hospitality furniture integration, traceable scope, and delivery boundaries</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>Client need / source status</h3><p>The source records a 28-room boutique hotel in central Taipei, with six levels organised around Idea, Notation, Reason, and Type concepts. The original material does not state the client problem in enough detail to verify it, so it is not inferred from photos.</p></article><article class=\"location-card reveal\"><h3>Space and furniture scope</h3><p>Verifiable guestroom furniture includes wardrobe, beverage minibar, writing desk, side table, bed headboard, and bed frame. The direction is to create a coherent hospitality furniture language between classic and modern cues.</p></article><article class=\"location-card reveal\"><h3>Material and design language</h3><p>Expanded mesh is the primary design element, with mesh + wood, mesh + pipe, mesh + lighting, and mesh + pattern listed as mixed-material directions. Formal grades and finishes require drawing confirmation.</p></article><article class=\"location-card reveal\"><h3>Verifiable Big Fame scope</h3><p>The document describes Big Fame developing the furniture collection and coordinating its material and form language. It does not approve a complete contractual division, manufacturing responsibility, site installation, or final-delivery responsibility.</p></article><article class=\"location-card reveal\"><h3>Quantity, timing, and destination</h3><p>Twenty-eight rooms describe the spatial context, not a confirmed furniture purchasing quantity. Drawing revision, material specifications, samples, lead time, destination, and final delivery scope must be reconfirmed for a live project.</p></article><article class=\"location-card reveal\"><h3>Result and publication boundary</h3><p>This is a traceable hospitality-furniture design and collection-development record, not an approved client installation or complete-delivery result. Client authorization, price, quantity, and actual performance are not confirmed by the source.</p></article></div><p class=\"section-note reveal\">For a hospitality guestroom programme, share the room types and count, furniture list, spatial concept, dimensions, material direction, target schedule, and destination first; Big Fame can then confirm integration and production conditions.</p></div></section>""",
    "jp": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">宿泊施設家具の統合課題・追跡可能な範囲・納品境界</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>顧客課題／資料の状態</h3><p>台北中心部の28室ブティックホテルについて、Idea、Notation、Reason、Type のコンセプトを6階層に整理した資料です。原資料だけでは顧客課題を十分に確認できないため、写真から推測していません。</p></article><article class=\"location-card reveal\"><h3>空間と家具範囲</h3><p>確認できる客室家具は、ワードローブ、ミニバー、ライティングデスク、サイドテーブル、ヘッドボード、ベッドフレームです。クラシックとモダンを一つの宿泊施設家具言語にまとめる方向です。</p></article><article class=\"location-card reveal\"><h3>素材とデザイン言語</h3><p>エキスパンドメタルを主な要素とし、mesh + wood、mesh + pipe、mesh + lighting、mesh + pattern の異素材方向を記録しています。正式な材質グレードと仕上げは図面で確認します。</p></article><article class=\"location-card reveal\"><h3>確認できる Big Fame の範囲</h3><p>資料には家具シリーズの開発と、素材・形状の言語をまとめる役割が記載されています。完全な契約分担、製造責任、現場施工、最終納品責任は承認確認できません。</p></article><article class=\"location-card reveal\"><h3>数量・納期・納品先</h3><p>28室は空間背景であり、家具の確定購買数量を意味しません。図面版、材料仕様、サンプル、納期、納品先、最終納入範囲は実案件ごとに再確認します。</p></article><article class=\"location-card reveal\"><h3>成果と公開範囲</h3><p>追跡可能な宿泊施設家具の設計・シリーズ開発記録であり、承認済みの顧客施工や完全納品の結果とは異なります。顧客許諾、価格、数量、実際の成果は資料上確認できません。</p></article></div><p class=\"section-note reveal\">宿泊施設の客室家具を計画する場合は、客室タイプと室数、家具リスト、空間コンセプト、寸法、素材、希望時期、納品先をご提示ください。統合と製作条件を確認します。</p></div></section>""",
}


for language, brief in BRIEFS.items():
    for path in (ROOT / language / "case-boutique-hotel-furniture.html", ROOT / language / "case-boutique-hotel-furniture" / "index.html"):
        source = path.read_text(encoding="utf-8")
        if 'data-bf-case-brief="1"' in source:
            continue
        marker = '<section class="section section-light" data-bf-faq="1">'
        if marker not in source:
            raise SystemExit(f"FAQ marker missing: {path}")
        path.write_text(source.replace(marker, brief + marker, 1), encoding="utf-8")
        print(path.relative_to(ROOT))
