"""Add an evidence-bounded brief to the anonymous wine-bar case."""
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

BRIEFS = {
    "tw": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">酒吧展示需求、可核對內容與公開邊界</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>客戶問題／來源狀態</h3><p>頁面記錄一個台北匿名酒吧的酒類展示櫃專案，核心問題是把酒類展示、展示照明與空間氛圍整合；目前沒有可公開核對的客戶名稱或原始需求文件。</p></article><article class=\"location-card reveal\"><h3>店型與使用情境</h3><p>店型可由頁面確認為酒吧／旅宿餐飲類展示情境，使用場景包含酒類展示櫃與櫃內照明；不延伸宣稱為特定品牌或連鎖店案例。</p></article><article class=\"location-card reveal\"><h3>Big Fame 可核對範圍</h3><p>目前可核對的是展示櫃方向、展示照明方向、KANEKA OLED light panel 的頁面紀錄，以及材質與配置討論；製造、安裝、採購協調與現場責任尚未由公開資料確認。</p></article><article class=\"location-card reveal\"><h3>可核對產品與材料</h3><p>可核對的展示內容包含酒類展示櫃與 KANEKA OLED light panel。完整材料牌號、板厚、表面處理、尺寸與固定方式，需依圖面、樣品或正式規格再確認。</p></article><article class=\"location-card reveal\"><h3>數量、交期與交付地</h3><p>公開資料未確認數量、MOQ、交期、交付地與正式商業條件，因此不把此案例延伸成通用的報價或交期承諾。</p></article><article class=\"location-card reveal\"><h3>成果與公開邊界</h3><p>這是匿名的空間展示方向與專案紀錄，不等同已核准的完成交付或現場施工成果；客戶名稱、訂單、授權與實際成效仍待確認。</p></article></div><p class=\"section-note reveal\">若要評估酒吧、餐飲或旅宿展示，請先提供店型、展示品項、櫃體尺寸、照明需求、數量、希望時程與交付地，Big Fame 再依專案條件確認。</p></div></section>""",
    "en": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">Wine-bar display need, verifiable content, and publication boundaries</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>Client need / source status</h3><p>The page records an anonymous Taipei wine-bar project. The documented direction combines wine display, cabinet lighting, and the atmosphere of the space; no client name or publishable original brief is available.</p></article><article class=\"location-card reveal\"><h3>Store context</h3><p>The page supports a bar and hospitality-food-service display context, including a wine display cabinet and integrated cabinet lighting. It is not extended into a named brand or chain-store claim.</p></article><article class=\"location-card reveal\"><h3>Verifiable Big Fame scope</h3><p>Currently verifiable: the display-cabinet direction, lighting direction, the KANEKA OLED light panel record, and discussion of material and configuration. Manufacturing, installation, procurement coordination, and site responsibility are not confirmed by the public evidence.</p></article><article class=\"location-card reveal\"><h3>Verifiable products and materials</h3><p>The display content includes a wine display cabinet and KANEKA OLED light panel. Formal material grade, thickness, finish, dimensions, and mounting method require drawings, samples, or approved specifications.</p></article><article class=\"location-card reveal\"><h3>Quantity, timing, and destination</h3><p>Public materials do not confirm quantity, MOQ, lead time, destination, or final commercial terms. This record is not extended into a general quotation or lead-time promise.</p></article><article class=\"location-card reveal\"><h3>Result and publication boundary</h3><p>This is an anonymous spatial-display direction and project record, not an approved completed delivery or site-installation result. Client name, order, authorization, and actual outcome remain unconfirmed.</p></article></div><p class=\"section-note reveal\">For a bar, restaurant, or hospitality display review, share the venue type, displayed products, cabinet dimensions, lighting need, quantity, timing, and destination first; Big Fame can then confirm the project path.</p></div></section>""",
    "jp": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">バー展示の課題・確認可能な内容・公開範囲</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>顧客課題／資料の状態</h3><p>台北の匿名ワインバー案件として、酒類展示、展示照明、空間の雰囲気を一体化する方向を記録しています。公開可能な顧客名や原始要望書は確認できません。</p></article><article class=\"location-card reveal\"><h3>店舗・利用シーン</h3><p>バーまたは宿泊・飲食空間の展示シーンとして、酒類展示棚と棚内照明を確認できます。特定ブランドやチェーン店舗の案件とは表記していません。</p></article><article class=\"location-card reveal\"><h3>確認できる Big Fame の範囲</h3><p>展示棚の方向、照明の方向、KANEKA OLED light panel の記録、材質・構成の検討を確認できます。製造、施工、購買調整、現場責任は公開資料では確認できません。</p></article><article class=\"location-card reveal\"><h3>確認できる製品・材料</h3><p>確認できる展示内容は酒類展示棚と KANEKA OLED light panel です。正式な材質、板厚、仕上げ、寸法、固定方法は図面・サンプル・承認仕様で確認します。</p></article><article class=\"location-card reveal\"><h3>数量・納期・納品先</h3><p>数量、MOQ、納期、納品先、最終商業条件は公開資料上確認できません。この記録を一般的な見積り・納期の約束として拡張していません。</p></article><article class=\"location-card reveal\"><h3>成果と公開範囲</h3><p>匿名の空間展示方向と案件記録であり、承認済みの納品完了・現場施工結果とは異なります。顧客名、注文、公開許諾、実際の成果は未確認です。</p></article></div><p class=\"section-note reveal\">バー、飲食、宿泊施設の展示を検討する場合は、店舗種別、展示品、棚寸法、照明条件、数量、希望時期、納品先をご提示ください。案件条件に応じて確認します。</p></div></section>""",
}


for language, brief in BRIEFS.items():
    for path in (ROOT / language / "case-japanese-wine-bar.html", ROOT / language / "case-japanese-wine-bar" / "index.html"):
        source = path.read_text(encoding="utf-8")
        if 'data-bf-case-brief="1"' in source:
            continue
        marker = '<section class="section section-light" data-bf-faq="1">'
        if marker not in source:
            raise SystemExit(f"FAQ marker missing: {path}")
        path.write_text(source.replace(marker, brief + marker, 1), encoding="utf-8")
        print(path.relative_to(ROOT))
