"""Add an evidence-bounded brief to the retail procurement integration case."""
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

BRIEFS = {
    "tw": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">多品類店面採購整合、文件證據與交付邊界</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>採購問題／來源狀態</h3><p>來源包含店面什器訂購清單與三組歷史 Pro Forma Invoice，需求涵蓋層板、掛勾、壓克力盒、桌架、衣架、POP 與化妝品展示配件；客戶與品牌名稱不公開。</p></article><article class=\"location-card reveal\"><h3>店型與展示範圍</h3><p>可核對的方向包含 wall bay、floor bay、gondola、table、hanger、signage、acrylic accessory 與 cosmetics display，對應牆面、島架與桌面展示的整合採購。</p></article><article class=\"location-card reveal\"><h3>產品與材料方向</h3><p>來源品項包含木製層板與桌架、鋼製掛勾／支架、壓克力盒與階梯架、PET 分隔板、POP 盒與標示配件；正式材料牌號、板厚與表面處理依圖面與樣品確認。</p></article><article class=\"location-card reveal\"><h3>Big Fame 可核對範圍</h3><p>文件識別與簽署區支持 Big Fame 參與品項整理、PI／報價文件與採購協調；來源不足以單獨證明每一品項的製造、安裝或最終現場交付責任。</p></article><article class=\"location-card reveal\"><h3>數量、交期與交付地</h3><p>歷史文件使用 PC、SET 等單位並記錄部分尺寸；PI 有台灣出貨、海外目的地與時程欄位，但公開版不揭露正式數量、目的地與時程，也不把歷史欄位當成目前承諾。</p></article><article class=\"location-card reveal\"><h3>成果與公開邊界</h3><p>這是匿名採購與文件整合紀錄，可用來理解多品類需求如何被拆分與確認，不等同特定客戶完成安裝、完整報價或最終現場成果。</p></article></div><p class=\"section-note reveal\">若要整合店面展示架、掛勾、壓克力配件、桌架或標示配件，請提供店型、區域、商品尺寸、品類清單、數量、包裝、交付地與時程，Big Fame 再逐項確認。</p></div></section>""",
    "en": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">Multi-category retail procurement integration, document evidence, and boundaries</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>Procurement problem / source status</h3><p>The sources include a retail-fixture order list and three historical pro forma invoices covering shelves, hooks, acrylic boxes, tables, hangers, POP, and beauty-display accessories. Client and brand names are withheld.</p></article><article class=\"location-card reveal\"><h3>Store and display scope</h3><p>Verifiable directions include wall bays, floor bays, gondolas, tables, hangers, signage, acrylic accessories, and cosmetics display, connecting wall, island, and tabletop procurement.</p></article><article class=\"location-card reveal\"><h3>Products and material directions</h3><p>Source items include wooden shelves and tables, steel hooks and brackets, acrylic boxes and stepped racks, PET dividers, POP cases, and signage accessories. Formal grades, thicknesses, and finishes require drawings and samples.</p></article><article class=\"location-card reveal\"><h3>Verifiable Big Fame scope</h3><p>Document identification and signature areas support Big Fame participation in item consolidation, PI / quotation documents, and procurement coordination. The sources do not alone prove manufacturing, installation, or final site-delivery responsibility for every item.</p></article><article class=\"location-card reveal\"><h3>Quantity, timing, and destination</h3><p>Historical documents use units such as PC and SET and include selected dimensions. PIs contain Taiwan-shipment, overseas-destination, and schedule fields, but the public version withholds formal quantity, destination, and timing and does not present historical fields as current promises.</p></article><article class=\"location-card reveal\"><h3>Result and publication boundary</h3><p>This is an anonymous procurement and document-integration record showing how multi-category requirements can be separated and confirmed. It is not a named completed installation, complete public quotation, or final site-result claim.</p></article></div><p class=\"section-note reveal\">For an integrated fixture request covering hooks, acrylic accessories, tables, or signage, share the store type, zones, product dimensions, category list, quantity, packing, destination, and schedule; Big Fame can then confirm each item.</p></div></section>""",
    "jp": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">多品目店舗什器の調達統合・資料証拠・納品境界</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>調達課題／資料の状態</h3><p>店舗什器の発注リストと3組の過去PIがあり、棚、フック、アクリルボックス、テーブル、ハンガー、POP、化粧品什器まで含みます。顧客名とブランド名は非公開です。</p></article><article class=\"location-card reveal\"><h3>店舗・展示範囲</h3><p>wall bay、floor bay、gondola、table、hanger、signage、アクリルアクセサリー、化粧品展示の方向を確認でき、壁面・島什器・卓上展示を調達条件へつなぎます。</p></article><article class=\"location-card reveal\"><h3>製品・材料の方向</h3><p>木製棚・テーブル、金属フック・ブラケット、アクリルボックス・段差ラック、PET仕切り、POPケース、表示アクセサリーが記録されています。正式材質・板厚・仕上げは図面とサンプルで確認します。</p></article><article class=\"location-card reveal\"><h3>確認できる Big Fame の範囲</h3><p>文書識別と署名欄から、品目整理、PI／見積資料、調達調整への関与を確認できます。ただし、全品目の製造、施工、最終納品責任を資料だけで断定しません。</p></article><article class=\"location-card reveal\"><h3>数量・納期・納品先</h3><p>過去資料には PC、SET 単位と一部寸法があります。PIには台湾出荷、海外納品先、予定時期の欄がありますが、公開版では正式数量、納品先、時期を伏せ、現在の約束として扱いません。</p></article><article class=\"location-card reveal\"><h3>成果と公開範囲</h3><p>多品目の要件を分けて確認する方法を示す匿名の調達・資料統合記録です。特定店舗の完成施工、公開見積、最終現場結果を主張するものではありません。</p></article></div><p class=\"section-note reveal\">什器、フック、アクリル、テーブル、表示用品を一括で検討する場合は、店舗タイプ、ゾーン、商品寸法、品目、数量、梱包、納品先、希望時期をご提示ください。項目ごとに確認します。</p></div></section>""",
}


for language, brief in BRIEFS.items():
    for path in (ROOT / language / "case-retail-fixture-procurement-integration.html", ROOT / language / "case-retail-fixture-procurement-integration" / "index.html"):
        source = path.read_text(encoding="utf-8")
        if 'data-bf-case-brief="1"' in source:
            continue
        marker = '<section class="section section-light" data-bf-faq="1">'
        if marker not in source:
            raise SystemExit(f"FAQ marker missing: {path}")
        path.write_text(source.replace(marker, brief + marker, 1), encoding="utf-8")
        print(path.relative_to(ROOT))
