"""Add an evidence-bounded case brief to the PAGE cosmetic organizer case."""
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

BRIEFS = {
    "tw": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">產品開發問題、可核對規格與交付邊界</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>客戶問題／來源狀態</h3><p>來源為 2020-03-30 ver.01 的 PAGE Offer Form，記錄桌上型美妝收納展示器的開發需求；原始資料未提供可完整核對的客戶名稱或原話。</p></article><article class=\"location-card reveal\"><h3>店型與使用情境</h3><p>可合理對應美容櫃位、桌上型商品陳列與品牌展示；來源資料沒有正式標註店型，因此不把它宣稱為已驗證的店面落地案例。</p></article><article class=\"location-card reveal\"><h3>Big Fame 可核對範圍</h3><p>目前可核對的是 Offer Form、圖面、產品圖，以及尺寸、材質、包裝與交期紀錄；正式合約角色、完整製造範圍與現場安裝責任尚未取得授權證據。</p></article><article class=\"location-card reveal\"><h3>可核對產品與條件</h3><p>W250 × D120 × H240 mm；透明壓克力、修邊拋光、實木；1 SET/CTN；樣品 15–25 天，量產在訂單確認後 25–35 天。以上僅適用於這份版本化紀錄。</p></article><article class=\"location-card reveal\"><h3>數量、MOQ 與目的地</h3><p>原始資料未確認數量、MOQ、出貨目的地與最終採購條件，因此不把單一案件資料延伸成 Big Fame 的通用承諾。</p></article><article class=\"location-card reveal\"><h3>成果與公開邊界</h3><p>這是可用於產品開發與報價溝通的文件證據，不等同已核准的客戶交付或完成安裝案例；客戶名稱、訂單、授權與實際使用成果仍待確認。</p></article></div><p class=\"section-note reveal\">採購或設計評估時，可先提供尺寸、材質、數量、目的地與交期需求，Big Fame 再依專案條件確認可行方案。</p></div></section>""",
    "en": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">Development need, verifiable specifications, and delivery boundaries</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>Client need / source status</h3><p>The source is a PAGE Offer Form, version 01 dated 2020-03-30, recording a tabletop cosmetic organizer development need. The source does not provide a fully verifiable client name or original brief.</p></article><article class=\"location-card reveal\"><h3>Store context</h3><p>The item can reasonably support beauty-counter, tabletop merchandising, and brand-display scenarios. The source does not formally classify the store, so this is not presented as a verified store-installation case.</p></article><article class=\"location-card reveal\"><h3>Verifiable Big Fame scope</h3><p>Currently verifiable: the Offer Form, drawing, product image, dimensions, materials, packing, and lead-time record. Contractual role, complete manufacturing scope, and site-installation responsibility are not authorized by the available evidence.</p></article><article class=\"location-card reveal\"><h3>Verifiable product and terms</h3><p>W250 × D120 × H240 mm; clear acrylic, edge polished, and solid wood; 1 SET/CTN; sample 15–25 days and bulk 25–35 days after order confirmation. These terms apply only to this versioned record.</p></article><article class=\"location-card reveal\"><h3>Quantity, MOQ, and destination</h3><p>Quantity, MOQ, shipping destination, and final purchasing terms are not confirmed in the source. A single record is not extended into a general Big Fame promise.</p></article><article class=\"location-card reveal\"><h3>Result and publication boundary</h3><p>This is documented evidence for product development and quotation discussion, not an approved client delivery or completed-installation case. Client name, order, authorization, and actual-use result remain unconfirmed.</p></article></div><p class=\"section-note reveal\">For a procurement or design review, share target dimensions, materials, quantity, destination, and timing first; Big Fame can then confirm feasibility for the project.</p></div></section>""",
    "jp": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">開発課題・確認可能な仕様・納品範囲</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>顧客課題／資料の状態</h3><p>出典は 2020-03-30 ver.01 の PAGE Offer Form で、卓上型コスメオーガナイザーの開発要望を記録しています。資料上、顧客名や原文の要望は完全には確認できません。</p></article><article class=\"location-card reveal\"><h3>店舗・利用シーン</h3><p>美容カウンター、卓上陳列、ブランド展示に対応し得る製品です。ただし資料に店舗種別の正式記載はないため、確認済みの店舗施工事例とは表記していません。</p></article><article class=\"location-card reveal\"><h3>確認できる Big Fame の範囲</h3><p>Offer Form、図面、製品画像、寸法、材質、梱包、納期記録を確認できます。契約上の役割、製造範囲全体、現場施工責任は、現時点の資料では承認確認できません。</p></article><article class=\"location-card reveal\"><h3>確認できる製品仕様・条件</h3><p>W250 × D120 × H240 mm、透明アクリル、エッジ研磨、無垢材、1 SET/CTN。サンプル 15–25 日、量産は注文確認後 25–35 日です。この条件は当該バージョンの記録に限ります。</p></article><article class=\"location-card reveal\"><h3>数量・MOQ・納品先</h3><p>数量、MOQ、出荷先、最終購買条件は資料上確認できません。単一案件の記録を Big Fame の一般的な約束として拡張していません。</p></article><article class=\"location-card reveal\"><h3>成果と公開範囲</h3><p>製品開発・見積り検討に使える記録であり、承認済みの顧客納品・施工完了事例とは異なります。顧客名、注文、公開許諾、実使用結果は未確認です。</p></article></div><p class=\"section-note reveal\">購買・設計の検討時は、寸法、材質、数量、納品先、希望納期をご提示ください。プロジェクト条件に応じて実現可能性を確認します。</p></div></section>""",
}


for language, brief in BRIEFS.items():
    flat = ROOT / language / "case-page-cosmetic-organizer.html"
    clean = ROOT / language / "case-page-cosmetic-organizer" / "index.html"
    for path in (flat, clean):
        source = path.read_text(encoding="utf-8")
        if 'data-bf-case-brief="1"' in source:
            continue
        marker = '<section class="section section-light" data-bf-faq="1">'
        if marker not in source:
            raise SystemExit(f"FAQ marker missing: {path}")
        path.write_text(source.replace(marker, brief + marker, 1), encoding="utf-8")
        print(path.relative_to(ROOT))
