"""Add an evidence-bounded brief to the hair-care display engineering case."""
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

BRIEFS = {
    "tw": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">髮品／美妝展示架需求、規格證據與歷史條件</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>客戶問題／來源狀態</h3><p>來源圖面從髮品盒尺寸出發，整理端架與雙面旋轉架的展示需求；正式客戶名稱與完整商業背景未公開。</p></article><article class=\"location-card reveal\"><h3>店型與展示情境</h3><p>端架適合靠牆或走道端面，雙面旋轉架適合中島與多方向取貨的零售動線；產品情境涵蓋美妝、髮品與小型盒裝商品。</p></article><article class=\"location-card reveal\"><h3>可核對產品與尺寸</h3><p>端架約 W23 × D13 5/8 × H66 5/8 英吋，來源標示容量 20 箱；雙面旋轉架約 W24 × D24 × H72 1/2 英吋，來源標示容量 40 箱。這些是歷史工程紀錄，不是現行承重保證。</p></article><article class=\"location-card reveal\"><h3>材質與 Big Fame 範圍</h3><p>可核對白色壓克力板、白色粉體塗裝金屬框架、9 槽壓克力槽板、壓克力招牌，以及白色粉體或鍍鉻鋼線掛勾；正式板厚、線徑、加工與合約責任需依核准圖面確認。</p></article><article class=\"location-card reveal\"><h3>樣品、運輸與歷史交期</h3><p>來源包含材料替代、樣品、共用框架、旋轉軸、槽板調整與拆解運輸的討論；歷史報價曾記錄樣品預估 3 週與出貨欄位，公開頁不把它當成目前交期。</p></article><article class=\"location-card reveal\"><h3>數量、MOQ 與公開邊界</h3><p>展示容量是來源圖面條件，不等同訂單數量、MOQ 或承重承諾。客戶、價格、正式數量、目的地、現行交期、安裝與最終交付結果未由來源核准。</p></article></div><p class=\"section-note reveal\">若要規劃端架、旋轉架、槽板或壓克力展示，請提供商品盒尺寸、展示數量、取貨方向、店型、交貨地與目標時程，再確認圖面、樣品與量產條件。</p></div></section>""",
    "en": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">Hair-care and beauty display need, specification evidence, and historical terms</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>Client need / source status</h3><p>The source drawings begin with hair-box dimensions and organise an end-cap and two-way-spinner display requirement. Client name and complete commercial background are not public.</p></article><article class=\"location-card reveal\"><h3>Store and display context</h3><p>The end cap suits a wall or aisle-end position, while the two-way spinner suits an island and multi-direction access. The product context covers beauty, hair-care, and small boxed goods.</p></article><article class=\"location-card reveal\"><h3>Verifiable products and dimensions</h3><p>The end-cap drawing records approximately W23 × D13 5/8 × H66 5/8 in with a source-stated capacity of 20 boxes. The two-way spinner records approximately W24 × D24 × H72 1/2 in with a source-stated capacity of 40 boxes. These are historical engineering records, not current load guarantees.</p></article><article class=\"location-card reveal\"><h3>Materials and Big Fame scope</h3><p>Verifiable directions include white acrylic panels, a white powder-coated metal frame, a nine-slot acrylic board, an acrylic header, and white powder-coated or chrome wire hooks. Final thickness, wire diameter, processing, and contractual scope require approved drawings.</p></article><article class=\"location-card reveal\"><h3>Samples, transport, and historical timing</h3><p>The sources discuss material alternatives, samples, shared frames, rotating axis, slot-board adjustment, and knock-down transport. A historical quotation records an estimated three-week sample lead time and shipment fields; the public page does not present it as current timing.</p></article><article class=\"location-card reveal\"><h3>Quantity, MOQ, and publication boundary</h3><p>Source-stated display capacity is a drawing condition, not order quantity, MOQ, or a load promise. Client, price, formal quantity, destination, current lead time, installation, and final delivery result are not approved by the source.</p></article></div><p class=\"section-note reveal\">For an end cap, spinner, slot board, or acrylic display review, share package dimensions, display quantity, access direction, store type, destination, and target schedule first; drawings, samples, and production conditions can then be confirmed.</p></div></section>""",
    "jp": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">ヘアケア・美容展示の課題・仕様資料・過去条件</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>顧客課題／資料の状態</h3><p>原図面はヘアケア商品の箱寸法から、エンドキャップと両面回転ラックの展示要件を整理しています。顧客名と完全な商取引背景は非公開です。</p></article><article class=\"location-card reveal\"><h3>店舗・展示シーン</h3><p>エンドキャップは壁面や通路端、両面回転ラックは島什器や複数方向から取る売場に適した方向です。美容、ヘアケア、小型箱入り商品を対象にしています。</p></article><article class=\"location-card reveal\"><h3>確認できる製品・寸法</h3><p>エンドキャップは約 W23 × D13 5/8 × H66 5/8 inch、資料上の容量20箱。両面回転ラックは約 W24 × D24 × H72 1/2 inch、資料上の容量40箱です。過去の工程記録であり、現行の耐荷重保証ではありません。</p></article><article class=\"location-card reveal\"><h3>素材と Big Fame の範囲</h3><p>白色アクリル板、白色粉体塗装金属フレーム、9スロットのアクリル板、アクリルヘッダー、白色粉体塗装またはクロームのワイヤーフックを確認できます。正式な板厚、線径、加工、契約範囲は承認図面で確認します。</p></article><article class=\"location-card reveal\"><h3>サンプル・輸送・過去納期</h3><p>材料代替、サンプル、共通フレーム、回転軸、スロット調整、分解輸送の検討があります。過去見積にはサンプル想定3週間と出荷欄がありますが、現在の納期として表示していません。</p></article><article class=\"location-card reveal\"><h3>数量・MOQ・公開範囲</h3><p>資料上の収納数は図面条件であり、注文数量、MOQ、耐荷重の約束ではありません。顧客、価格、正式数量、納品先、現在の納期、施工、最終納品結果は承認確認できません。</p></article></div><p class=\"section-note reveal\">エンドキャップ、回転ラック、スロットボード、アクリル展示を検討する場合は、商品の箱寸法、展示数量、取り出し方向、店舗タイプ、納品先、希望時期をご提示ください。図面、サンプル、量産条件を確認します。</p></div></section>""",
}


for language, brief in BRIEFS.items():
    for path in (ROOT / language / "case-hair-display-spinner-engineering.html", ROOT / language / "case-hair-display-spinner-engineering" / "index.html"):
        source = path.read_text(encoding="utf-8")
        if 'data-bf-case-brief="1"' in source:
            continue
        marker = '<section class="section section-light" data-bf-faq="1">'
        if marker not in source:
            raise SystemExit(f"FAQ marker missing: {path}")
        path.write_text(source.replace(marker, brief + marker, 1), encoding="utf-8")
        print(path.relative_to(ROOT))
