"""Add an evidence-bounded brief to the second-hand 3C modular case."""
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

BRIEFS = {
    "tw": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">模組化 3C 門市需求、交付欄位與複製邊界</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>客戶問題／來源狀態</h3><p>來源需求是建立具風格的二手 3C 門市，展示 MacBook Air、iPhone、iPad、iMac、相機與遊戲主機，並希望系統能支援其他城市展店；客戶名稱與原始完整文件未公開。</p></article><article class=\"location-card reveal\"><h3>店型與使用情境</h3><p>店型為二手 3C 零售門市，來源提及台北首店與後續展店構想；展示情境包含壁面、玻璃櫃與落地櫃，並需要兼顧高價電子產品的陳列與管理。</p></article><article class=\"location-card reveal\"><h3>可核對展示系統</h3><p>可核對的交付方向包含矩形管與水平連接管組成的壁面展示系統、玻璃展示櫃、落地展示櫃，以及可替換功能上蓋的共用櫃體。</p></article><article class=\"location-card reveal\"><h3>材料與 Big Fame 範圍</h3><p>來源提及合板、夾板、金屬、玻璃與燈光；正式材料牌號、完整圖面與合約分工未公開。可確認的是展示系統與模組化方向的開發紀錄，不延伸宣稱全部製造或現場安裝責任。</p></article><article class=\"location-card reveal\"><h3>交付與部署條件</h3><p>需求包含易運輸、易組裝與跨店複製方向；最終交付地、包裝方式、數量、MOQ 與交期未公開，新的店面仍需依平面、商品、數量與目的地確認。</p></article><article class=\"location-card reveal\"><h3>成果與公開邊界</h3><p>這是匿名的模組化店面系統需求與交付欄位紀錄，不等同已公開完整報價、客戶成效或跨城市實際部署結果；客戶名稱、完整圖面與成效數字不公開。</p></article></div><p class=\"section-note reveal\">若要評估可複製的 3C 或高單價商品門市，請先提供平面、商品、展示數量、模組功能、包裝、展店城市與時程，Big Fame 再確認可行的系統與交付範圍。</p></div></section>""",
    "en": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">Modular 3C store need, delivery fields, and repeatability boundaries</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>Client need / source status</h3><p>The source need was a distinctive second-hand 3C store for MacBook Air, iPhone, iPad, iMac, cameras, and game consoles, with a system that could support expansion to other cities. Client name and complete original documents are not public.</p></article><article class=\"location-card reveal\"><h3>Store context</h3><p>The store type is second-hand 3C retail. The source mentions a first Taipei store and expansion intent, with wall, glass, and floor-standing display conditions for high-value electronics.</p></article><article class=\"location-card reveal\"><h3>Verifiable display system</h3><p>Verifiable directions include a wall display system made from rectangular pipe and horizontal connectors, glass showcases, floor-standing showcases, and shared cabinets with replaceable functional tops.</p></article><article class=\"location-card reveal\"><h3>Materials and Big Fame scope</h3><p>The source mentions composite board, plywood, metal, glass, and lighting. Formal grades, complete drawings, and contractual division are not public. The evidence supports development of the display system and modular direction, not an automatic claim for all manufacturing or site installation.</p></article><article class=\"location-card reveal\"><h3>Delivery and deployment conditions</h3><p>The brief includes easy shipping, easy assembly, and repeatability across stores. Final destination, packing method, quantity, MOQ, and lead time are not public; each new store requires review against its plan, products, quantity, and destination.</p></article><article class=\"location-card reveal\"><h3>Result and publication boundary</h3><p>This is an anonymous modular-store need and delivery-field record, not a public claim of complete quotation, client performance, or actual multi-city deployment. Client name, complete drawings, and performance figures are withheld.</p></article></div><p class=\"section-note reveal\">For a repeatable 3C or high-value-product store, share the plan, products, display quantity, module functions, packing, rollout cities, and timing first; Big Fame can then confirm the feasible system and delivery scope.</p></div></section>""",
    "jp": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">モジュール型3C店舗の課題・納品項目・展開範囲</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>顧客課題／資料の状態</h3><p>MacBook Air、iPhone、iPad、iMac、カメラ、ゲーム機を扱う特徴的な中古3C店舗をつくり、他都市にも展開できる展示システムを求めた記録です。顧客名と完全な原資料は非公開です。</p></article><article class=\"location-card reveal\"><h3>店舗・利用シーン</h3><p>中古3C小売で、資料には台北の初店舗と展開構想が記載されています。高額電子製品を壁面、ガラスケース、床置きケースで展示する条件です。</p></article><article class=\"location-card reveal\"><h3>確認できる展示システム</h3><p>矩形パイプと水平連結による壁面システム、ガラスショーケース、床置きショーケース、交換式の機能天板を持つ共用キャビネットを確認できます。</p></article><article class=\"location-card reveal\"><h3>素材と Big Fame の範囲</h3><p>コンポジットボード、合板、金属、ガラス、照明の方向が資料にあります。正式グレード、完全図面、契約上の分担は非公開です。展示システムとモジュール化の開発記録を示すもので、全製造・現場施工を自動的に主張しません。</p></article><article class=\"location-card reveal\"><h3>納品・展開条件</h3><p>輸送、組立、複数店舗への展開を考えた方向が記録されています。最終納品先、梱包方法、数量、MOQ、納期は非公開で、新しい店舗ごとに平面、商品、数量、納品先を確認します。</p></article><article class=\"location-card reveal\"><h3>成果と公開範囲</h3><p>匿名のモジュール店舗要件と納品項目の記録であり、完全な見積り、顧客成果、複数都市への実展開を公開するものではありません。顧客名、完全図面、効果数値は掲載していません。</p></article></div><p class=\"section-note reveal\">展開可能な3C・高額商品店舗を検討する場合は、平面、商品、展示数量、モジュール機能、梱包、展開都市、時期をご提示ください。実現可能なシステムと納品範囲を確認します。</p></div></section>""",
}


for language, brief in BRIEFS.items():
    for path in (ROOT / language / "case-modular-3c-store.html", ROOT / language / "case-modular-3c-store" / "index.html"):
        source = path.read_text(encoding="utf-8")
        if 'data-bf-case-brief="1"' in source:
            continue
        marker = '<section class="section section-light" data-bf-faq="1">'
        if marker not in source:
            raise SystemExit(f"FAQ marker missing: {path}")
        path.write_text(source.replace(marker, brief + marker, 1), encoding="utf-8")
        print(path.relative_to(ROOT))
