"""Add an evidence-bounded brief to the headphone display engineering case."""
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

BRIEFS = {
    "tw": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">耳機展示工程需求、文件交付與公開邊界</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>客戶問題／來源狀態</h3><p>來源記錄三耳機展示組與多個通路版本，差異包含展示耳機、掛鉤貼紙、底部圖像與影音播放器；客戶名稱與正式合約範圍未公開。</p></article><article class=\"location-card reveal\"><h3>展示產品與結構</h3><p>可核對的工程方向包含真空成型外殼、金屬支撐件、背景圖像、按鈕、影音播放器與掛鉤組件，並以客戶圖面、零件編號與 BOM 對應。</p></article><article class=\"location-card reveal\"><h3>Big Fame 可核對範圍</h3><p>來源可核對展示結構、零件對應、鉚接與安裝步驟、電源線固定、工廠組裝說明，以及 Packout 與運輸保護文件；不延伸宣稱完整製造或客戶現場責任。</p></article><article class=\"location-card reveal\"><h3>包裝與組裝交付物</h3><p>Packout 記錄填充件、外箱、套管、展示本體、金屬支架、螺絲包與說明文件的裝箱配置；組裝文件記錄圖像貼合、按鈕與播放器安裝、鉚接與外殼組合。</p></article><article class=\"location-card reveal\"><h3>數量、交期與交付地</h3><p>公開資料未確認訂單數量、MOQ、交期、交付地與正式出貨結果，因此不把工程文件中的三耳機配置當成通用數量或商業承諾。</p></article><article class=\"location-card reveal\"><h3>成果與公開邊界</h3><p>這是匿名工程文件、組裝與包裝準備紀錄，能用於評估展示結構與工程溝通，不等同已核准的客戶交付或完成出貨案例。</p></article></div><p class=\"section-note reveal\">若要評估互動展示架，請提供展示產品、尺寸、固定方式、通路版本、數量、影音需求、包裝條件與時程，並附現有圖面或照片。</p></div></section>""",
    "en": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">Headphone display engineering need, documented deliverables, and boundaries</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>Client need / source status</h3><p>The source records a three-headphone display set with multiple channel versions. Differences include the displayed headphones, hook decals, bottom graphics, and an audio/video player; client name and formal contract scope are not public.</p></article><article class=\"location-card reveal\"><h3>Displayed products and structure</h3><p>Verifiable engineering directions include a vacuum-formed housing, metal supports, background graphics, buttons, an audio/video player, and hook assemblies, mapped through customer drawings, part numbers, and a BOM.</p></article><article class=\"location-card reveal\"><h3>Verifiable Big Fame scope</h3><p>The sources support display structure, part mapping, riveting and installation steps, power-cable retention, plant assembly instructions, and Packout and transport-protection records. They are not extended into a claim for all manufacturing or site responsibility.</p></article><article class=\"location-card reveal\"><h3>Packing and assembly deliverables</h3><p>Packout records identify fillers, carton, sleeve, display body, metal brackets, screw pack, and instructions. Assembly documents cover graphic placement, button and player installation, riveting, and housing-to-support assembly.</p></article><article class=\"location-card reveal\"><h3>Quantity, timing, and destination</h3><p>Public materials do not confirm order quantity, MOQ, lead time, destination, or formal shipment result. The three-headphone configuration is not treated as a universal quantity or commercial promise.</p></article><article class=\"location-card reveal\"><h3>Result and publication boundary</h3><p>This is an anonymous engineering, assembly, and packing-preparation record useful for evaluating display structure and engineering communication. It is not presented as an approved client delivery or completed-shipment case.</p></article></div><p class=\"section-note reveal\">For an interactive display review, share the displayed product, dimensions, retention method, channel versions, quantity, media needs, packing conditions, and schedule, together with any drawings or photos.</p></div></section>""",
    "jp": """<section class=\"section section-light\" data-bf-case-brief=\"1\"><div class=\"container\"><div class=\"section-heading reveal\"><span class=\"section-subtitle\">CASE BRIEF</span><h2 class=\"section-title\">ヘッドホン展示の設計課題・資料成果物・公開範囲</h2></div><div class=\"grid-3\"><article class=\"location-card reveal\"><h3>顧客課題／資料の状態</h3><p>3台のヘッドホン展示セットと複数チャネル仕様を記録しています。展示ヘッドホン、フック用グラフィック、底部グラフィック、映像プレーヤーが差分です。顧客名と正式契約範囲は非公開です。</p></article><article class=\"location-card reveal\"><h3>展示製品と構造</h3><p>顧客図面、部品番号、BOM に対応する真空成形ハウジング、金属支持部品、背景グラフィック、ボタン、映像プレーヤー、フック部品を確認できます。</p></article><article class=\"location-card reveal\"><h3>確認できる Big Fame の範囲</h3><p>展示構造、部品対応、リベット・取付手順、電源ケーブル固定、工場組立説明、Packout と輸送保護の記録を確認できます。全製造・現場責任の主張には拡張していません。</p></article><article class=\"location-card reveal\"><h3>梱包・組立の成果物</h3><p>Packout には緩衝材、外箱、スリーブ、展示本体、金属ブラケット、ねじ袋、説明書の配置があります。組立資料にはグラフィック、ボタン・プレーヤー、リベット、外装と支持部品の手順があります。</p></article><article class=\"location-card reveal\"><h3>数量・納期・納品先</h3><p>注文数量、MOQ、納期、納品先、正式な出荷結果は公開資料上確認できません。3台構成を一般的な数量や商業条件として扱っていません。</p></article><article class=\"location-card reveal\"><h3>成果と公開範囲</h3><p>展示構造とエンジニアリングコミュニケーションを検討できる匿名の設計・組立・梱包準備記録です。承認済みの顧客納品・出荷完了事例としては掲載していません。</p></article></div><p class=\"section-note reveal\">インタラクティブ展示を検討する場合は、展示製品、寸法、固定方法、チャネル仕様、数量、映像機器、梱包条件、希望時期、図面または写真をご提示ください。</p></div></section>""",
}


for language, brief in BRIEFS.items():
    for path in (ROOT / language / "case-headphone-display-set.html", ROOT / language / "case-headphone-display-set" / "index.html"):
        source = path.read_text(encoding="utf-8")
        if 'data-bf-case-brief="1"' in source:
            continue
        marker = '<section class="section section-light" data-bf-faq="1">'
        if marker not in source:
            raise SystemExit(f"FAQ marker missing: {path}")
        path.write_text(source.replace(marker, brief + marker, 1), encoding="utf-8")
        print(path.relative_to(ROOT))
