"""Add an evidence-safe visual index to the trilingual technical resource pages."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MARKER = '<section class="section section-light" data-bf-resource-catalog="1">'

SECTIONS = {
    "tw": '''<section class="section section-light" data-bf-resource-visual-index="1"><div class="container"><div class="section-heading reveal"><span class="section-subtitle">VISUAL RESOURCE INDEX</span><h2 class="section-title">先從使用情境找到資料入口</h2><p>以下是網站目前可公開查看的產品視覺參考；視覺不等於指定 SKU 或完整規格，請進入產品頁確認證據，再依需求索取圖面與材質資料。</p></div><div class="grid-3"><article class="location-card reveal"><img src="../images/product-display-hooks.jpg" alt="店面展示掛勾產品視覺參考" loading="lazy"><h3>展示掛勾</h3><p>從洞洞板、槽板與掛勾長度條件開始。</p><a href="display-hooks">查看展示掛勾產品頁</a></article><article class="location-card reveal"><img src="../images/product-optical-hooks.png" alt="眼鏡展示掛勾產品視覺參考" loading="lazy"><h3>眼鏡展示掛勾</h3><p>從眼鏡商品、展示密度與背板系統開始。</p><a href="optical-hooks">查看眼鏡掛勾產品頁</a></article><article class="location-card reveal"><img src="../images/product-slatwall-accessories.jpg" alt="槽板與洞洞板配件產品視覺參考" loading="lazy"><h3>槽板／洞洞板配件</h3><p>從安裝系統、層板與配件組合開始。</p><a href="slatwall-pegboard-accessories">查看配件產品頁</a></article><article class="location-card reveal"><img src="../images/product-price-tag-holders.jpg" alt="價格條與標示配件產品視覺參考" loading="lazy"><h3>價格條／標示配件</h3><p>從標示位置、尺寸與店內補貨使用開始。</p><a href="price-tag-holders">查看標示配件產品頁</a></article><article class="location-card reveal"><img src="../images/product-pos-displays-counter-catalog.jpg" alt="POS 檯面展示產品視覺參考" loading="lazy"><h3>POS／檯面展示</h3><p>從商品尺寸、檯面空間與展示用途開始。</p><a href="pos-displays">查看 POS 展示產品頁</a></article><article class="location-card reveal"><img src="../images/product-modular-fixtures-arc67.jpg" alt="模組化展示架產品視覺參考" loading="lazy"><h3>模組化展示架</h3><p>從店型、展示系統與配置變更開始。</p><a href="modular-fixtures">查看模組化展示架產品頁</a></article></div></div></section>''',
    "en": '''<section class="section section-light" data-bf-resource-visual-index="1"><div class="container"><div class="section-heading reveal"><span class="section-subtitle">VISUAL RESOURCE INDEX</span><h2 class="section-title">Start with the display situation</h2><p>These are public visual references currently available on the site. A visual is not a formal SKU or complete specification; use the product page for evidence, then request drawing and material data.</p></div><div class="grid-3"><article class="location-card reveal"><img src="../images/product-display-hooks.jpg" alt="Visual reference for retail display hooks" loading="lazy"><h3>Display hooks</h3><p>Start with pegboard, slatwall and hook-length conditions.</p><a href="display-hooks">View the display-hook product page</a></article><article class="location-card reveal"><img src="../images/product-optical-hooks.png" alt="Visual reference for eyewear display hooks" loading="lazy"><h3>Eyewear display hooks</h3><p>Start with the eyewear product, density and backing system.</p><a href="optical-hooks">View the eyewear-hook product page</a></article><article class="location-card reveal"><img src="../images/product-slatwall-accessories.jpg" alt="Visual reference for slatwall and pegboard accessories" loading="lazy"><h3>Slatwall / pegboard accessories</h3><p>Start with the mounting system, shelves and accessory mix.</p><a href="slatwall-pegboard-accessories">View the accessory product page</a></article><article class="location-card reveal"><img src="../images/product-price-tag-holders.jpg" alt="Visual reference for price-tag and sign holders" loading="lazy"><h3>Price tags / sign holders</h3><p>Start with sign position, size and replenishment use.</p><a href="price-tag-holders">View the sign-holder product page</a></article><article class="location-card reveal"><img src="../images/product-pos-displays-counter-catalog.jpg" alt="Visual reference for POS tabletop displays" loading="lazy"><h3>POS / tabletop displays</h3><p>Start with the product size, counter space and display purpose.</p><a href="pos-displays">View the POS display product page</a></article><article class="location-card reveal"><img src="../images/product-modular-fixtures-arc67.jpg" alt="Visual reference for modular retail fixtures" loading="lazy"><h3>Modular fixtures</h3><p>Start with the store type, display system and layout changes.</p><a href="modular-fixtures">View the modular-fixture product page</a></article></div></div></section>''',
    "jp": '''<section class="section section-light" data-bf-resource-visual-index="1"><div class="container"><div class="section-heading reveal"><span class="section-subtitle">VISUAL RESOURCE INDEX</span><h2 class="section-title">展示シーンから資料入口を探す</h2><p>以下は現在サイトで公開している製品ビジュアルの参考です。ビジュアルは正式 SKU や完全仕様を示しません。製品ページで証拠を確認し、図面や材料資料を相談してください。</p></div><div class="grid-3"><article class="location-card reveal"><img src="../images/product-display-hooks.jpg" alt="店舗用展示フックのビジュアル参考" loading="lazy"><h3>展示フック</h3><p>有孔ボード、スラットウォール、フック長さから確認します。</p><a href="display-hooks">展示フック製品ページ</a></article><article class="location-card reveal"><img src="../images/product-optical-hooks.png" alt="メガネ展示フックのビジュアル参考" loading="lazy"><h3>メガネ展示フック</h3><p>商品、展示密度、背板システムから確認します。</p><a href="optical-hooks">メガネフック製品ページ</a></article><article class="location-card reveal"><img src="../images/product-slatwall-accessories.jpg" alt="スラットウォールと有孔ボード用アクセサリーのビジュアル参考" loading="lazy"><h3>壁面システム用アクセサリー</h3><p>取付システム、棚、アクセサリーの組合せから確認します。</p><a href="slatwall-pegboard-accessories">アクセサリー製品ページ</a></article><article class="location-card reveal"><img src="../images/product-price-tag-holders.jpg" alt="プライスタグとサインホルダーのビジュアル参考" loading="lazy"><h3>プライスタグ／表示金具</h3><p>表示位置、寸法、補充作業から確認します。</p><a href="price-tag-holders">表示金具製品ページ</a></article><article class="location-card reveal"><img src="../images/product-pos-displays-counter-catalog.jpg" alt="POSと卓上ディスプレイのビジュアル参考" loading="lazy"><h3>POS／卓上ディスプレイ</h3><p>商品寸法、カウンター空間、展示目的から確認します。</p><a href="pos-displays">POS製品ページ</a></article><article class="location-card reveal"><img src="../images/product-modular-fixtures-arc67.jpg" alt="モジュール式展示什器のビジュアル参考" loading="lazy"><h3>モジュール式展示什器</h3><p>店舗タイプ、展示システム、レイアウト変更から確認します。</p><a href="modular-fixtures">モジュール製品ページ</a></article></div></div></section>''',
}

for locale, section in SECTIONS.items():
    path = ROOT / locale / "technical-resources.html"
    text = path.read_text(encoding="utf-8")
    if 'data-bf-resource-visual-index="1"' in text:
        continue
    if MARKER not in text:
        raise SystemExit(f"resource catalog marker not found: {locale}")
    path.write_text(text.replace(MARKER, section + MARKER, 1), encoding="utf-8", newline="")

print("Added visual resource indexes to tw/en/jp technical-resources pages.")
