from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SECTIONS = {
    "tw": '''<section class="section section-light" data-bf-source-record="1"><div class="container"><div class="section-header reveal"><span class="section-subtitle">SOURCE RECORD</span><h2 class="section-title">TA MUJI Valencia 採購文件來源紀錄</h2></div><div class="grid-3"><article class="location-card reveal"><h3>訂購清單</h3><p>來源包含店面什器訂購清單，品類涵蓋 wall bay、floor bay、層板、支架、掛勾、壓克力盒、桌架、衣架、gondola、POP 與標示配件。</p></article><article class="location-card reveal"><h3>PI 與規格欄位</h3><p>三組歷史 PI 分別整理一般備品、桌架／Miracle 與化妝品展示方向；文件可見 PC／SET 單位、部分 W／D／H 尺寸與商品用途。</p></article><article class="location-card reveal"><h3>Big Fame 工作證據</h3><p>PI／訂購文件具有 Big Fame 文件識別與簽署區，支持品項整理、商業文件與採購協調；不單獨證明每一品項由 Big Fame 製造、安裝或完成現場交付。</p></article></div><p class="section-note reveal">公開版不揭露客戶、品牌、PI 編號、正式數量、價格、目的地或歷史時程；這些文件是匿名採購證據，不是目前通用型錄、MOQ 或交期承諾。</p></div></section>''',
    "en": '''<section class="section section-light" data-bf-source-record="1"><div class="container"><div class="section-header reveal"><span class="section-subtitle">SOURCE RECORD</span><h2 class="section-title">TA MUJI Valencia procurement-document record</h2></div><div class="grid-3"><article class="location-card reveal"><h3>Order list</h3><p>The source includes a retail-fixture order list covering wall bays, floor bays, shelves, brackets, hooks, acrylic boxes, tables, hangers, gondola, POP and signage accessories.</p></article><article class="location-card reveal"><h3>PI and specification fields</h3><p>Three historical PIs organize general supplies, table／Miracle directions and beauty-display directions; the files show PC／SET units, selected W／D／H dimensions and product uses.</p></article><article class="location-card reveal"><h3>Big Fame work evidence</h3><p>The PI and order documents carry Big Fame document identification and signature areas, supporting item consolidation, commercial documents and procurement coordination; they do not alone prove Big Fame manufactured, installed or completed every item on site.</p></article></div><p class="section-note reveal">The public version omits client, brand, PI number, formal quantities, prices, destination and historical schedule. These are anonymous procurement records, not current universal catalogue, MOQ or lead-time commitments.</p></div></section>''',
    "jp": '''<section class="section section-light" data-bf-source-record="1"><div class="container"><div class="section-header reveal"><span class="section-subtitle">SOURCE RECORD</span><h2 class="section-title">TA MUJI Valencia 調達資料の出典記録</h2></div><div class="grid-3"><article class="location-card reveal"><h3>発注リスト</h3><p>出典には店舗什器の発注リストがあり、wall bay、floor bay、棚、ブラケット、フック、アクリルボックス、テーブル、ハンガー、gondola、POP、サイン用品を含みます。</p></article><article class="location-card reveal"><h3>PI と仕様欄</h3><p>3つの過去 PI は一般備品、テーブル／Miracle、化粧品展示の方向を整理し、PC／SET 単位、一部 W／D／H 寸法、用途を確認できます。</p></article><article class="location-card reveal"><h3>Big Fame の作業証拠</h3><p>PI と発注資料には Big Fame の文書識別と署名欄があり、品目整理、商業資料、調達調整を支えます。ただし全品目の製造、施工、現場納品を単独で証明するものではありません。</p></article></div><p class="section-note reveal">公開版では顧客、ブランド、PI 番号、正式数量、価格、納入先、過去のスケジュールを掲載しません。匿名の調達記録であり、現在の共通カタログ、MOQ、納期の約束ではありません。</p></div></section>''',
}

for language, section in SECTIONS.items():
    path = ROOT / language / "case-retail-fixture-procurement-integration.html"
    text = path.read_text(encoding="utf-8")
    marker = '<section class="section section-light" data-bf-faq="1">'
    if 'data-bf-source-record="1"' not in text:
        if text.count(marker) != 1:
            raise RuntimeError(f"unexpected marker count for {path}: {text.count(marker)}")
        path.write_text(text.replace(marker, section + marker, 1), encoding="utf-8")
        print(f"updated {path}")
